name: Experimenting EAS Android Build

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install Dependencies
      run: npm install
    - name: Setup Android Environment
      run: |
        # Install Android SDK
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip commandlinetools-linux-7583922_latest.zip -d android-sdk
        echo "ANDROID_SDK_ROOT=$GITHUB_WORKSPACE/android-sdk" >> $GITHUB_ENV
        echo "$GITHUB_WORKSPACE/android-sdk/cmdline-tools/bin" >> $GITHUB_PATH
        yes | android-sdk/cmdline-tools/bin/sdkmanager --licenses
        android-sdk/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

        # Install Android NDK
        android-sdk/cmdline-tools/bin/sdkmanager "ndk;21.4.7075529"
        echo "ANDROID_NDK_ROOT=$GITHUB_WORKSPACE/android-sdk/ndk/21.4.7075529" >> $GITHUB_ENV

        # Set environment variable for SDK and NDK
        echo "ANDROID_HOME=$GITHUB_WORKSPACE/android-sdk" >> $GITHUB_ENV
    - name: Build Android
      run: npx eas build --platform android --local --profile preview