name: iOS .app Build Workflow

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm ci

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          sudo gem install cocoapods -v 1.14.3
          pod install

      - name: Build iOS .app for Simulator (Release Mode)
        run: npx react-native run-ios --mode Release

      - name: Locate and Rename .app for Simulator
        run: |
          APP_PATH=$(find $HOME/Library/Developer/Xcode/DerivedData -name "ulshopify.app" -type d | head -n 1)
          echo "App Path: $APP_PATH"
          if [ -n "$APP_PATH" ]; then
            DEST_PATH="ios/build/Release-iphonesimulator/ul-shopify.app"
            mkdir -p $DEST_PATH
            cp -R "$APP_PATH"/* $DEST_PATH
          else
            echo "Error: .app file not found"
            exit 1
          fi
        id: rename-app

      - name: Zip the .app directory
        run: |
          cd ios/build/Release-iphonesimulator
          zip -r ul-shopify.app.zip ul-shopify.app
        id: zip-app

      - name: Upload .app Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ul-shopify-app
          path: ios/build/Release-iphonesimulator/ul-shopify.app.zip
