# To have .ipa file we must require development account

# name: iOS .ipa Build Workflow

# on:
#   workflow_dispatch:

# jobs:
#   build-ios:
#     runs-on: macos-latest
#     steps:
#       - name: Check out repository
#         uses: actions/checkout@v3

#       - name: Setup Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18'

#       - name: Install npm dependencies
#         run: npm ci

#       - name: Install CocoaPods dependencies
#         run: |
#           cd ios
#           sudo gem install cocoapods
#           pod install

#       - name: Archive iOS Project
#         run: |
#           cd ios
#           xcodebuild archive -workspace ulshopify.xcworkspace \
#                             -scheme ulshopify \
#                             -sdk iphoneos \
#                             -configuration Release \
#                             -archivePath $PWD/build/ulshopify.xcarchive

#       - name: Export .ipa File
#         run: |
#           xcodebuild -exportArchive -archivePath ios/build/ulshopify.xcarchive \
#                     -exportOptionsPlist exportOptions.plist \
#                     -exportPath ios/build \
#                     -archivePath ios/build/ulshopify.xcarchive
#           mv ios/build/ulshopify.ipa ios/build/ul-shopify.ipa

#       - name: Upload .ipa Artifact
#         uses: actions/upload-artifact@v3
#         with:
#           name: ul-shopify-ipa
#           path: ios/build/ul-shopify.ipa